[error] sbt.librarymanagement.ResolveException: Error downloading org.apache.spark:spark-core_2.13:3.0.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/attilavanderploeg/.ivy2/local/org.apache.spark/spark-core_2.13/3.0.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.13/3.0.1/spark-core_2.13-3.0.1.pom
[error] Error downloading org.apache.spark:spark-sql_2.13:3.0.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/attilavanderploeg/.ivy2/local/org.apache.spark/spark-sql_2.13/3.0.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.13/3.0.1/spark-sql_2.13-3.0.1.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at lmcoursier.CoursierDependencyResolution$$Lambda$4456/0000000000000000.apply(Unknown Source)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$3557/0000000000000000.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.util.Tracked$$$Lambda$3510/0000000000000000.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$3559/0000000000000000.apply(Unknown Source)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$3553/0000000000000000.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.util.Tracked$$$Lambda$3305/0000000000000000.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3485)
[error] 	at sbt.Classpaths$$$Lambda$700/0000000000000000.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at scala.Function1$$Lambda$378/0000000000000000.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$3194/0000000000000000.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$3217/0000000000000000.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.Execute$$Lambda$3204/0000000000000000.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$3212/0000000000000000.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:836)
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading org.apache.spark:spark-core_2.13:3.0.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/attilavanderploeg/.ivy2/local/org.apache.spark/spark-core_2.13/3.0.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.13/3.0.1/spark-core_2.13-3.0.1.pom
[error] Error downloading org.apache.spark:spark-sql_2.13:3.0.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/attilavanderploeg/.ivy2/local/org.apache.spark/spark-sql_2.13/3.0.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.13/3.0.1/spark-sql_2.13-3.0.1.pom
